# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57dd72d258b4721176ec8694333e75e4da727830c5a59fd9545ea836c43b49fd25339b1151d0fc16839e3a3c2a21745bb7f13cd5b736db5ff3126bd23c33c59a

test:
  secret_key_base: 5cafef3cc97b9edc2c5695c03229f159358f0d4b8edc42d841583d7d6722549403693abed6b8af3136e419648770807336527d520ba740bdb95657cc5326c4c6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
